apiVersion: externaldata.gatekeeper.sh/v1alpha1
kind: Provider
metadata:
  name: tagtodigest-provider
spec:
  proxyURL: http://tagtodigest-provider.default:8090/mutate
  timeout: 10
  failurePolicy: fail
  maxRetry: 5
