apiVersion: v1
kind: Namespace
metadata:
  name: external-data-providers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagtodigest-provider
  namespace: external-data-providers
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tagtodigest-provider
  template:
    metadata:
      labels:
        run: tagtodigest-provider
    spec:
      containers:
      - image: sozercan/tagtodigest-provider:v0.0.1
        imagePullPolicy: IfNotPresent
        name: tagtodigest-provider
        ports:
        - containerPort: 8090
          protocol: TCP
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: provider-tagtodigest-sa
