apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-tagtodigest-role
  namespace: external-data-providers
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - serviceaccounts
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-tagtodigest-rolebinding
  namespace: external-data-providers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-tagtodigest-role
subjects:
- kind: ServiceAccount
  name: provider-tagtodigest-sa
  namespace: external-data-providers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-tagtodigest-sa
  namespace: external-data-providers
