apiVersion: v1
kind: Service
metadata:
  name: tagtodigest-provider
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: tagtodigest-provider
  sessionAffinity: None
