name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@911b1af682b685d05d871fe5572549216219b577
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: 'Checkout Repository'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@467931ed7e779e3bb7518e878758ea0c339e388c # v1
