name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
      with:
        egress-policy: audit

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@032fa5c5e48499f06cf9d32c02149bfac1284239 # v3.2.0
      with:
        version: latest
